spring.application.name=uca-cfc-connect

# Puerto de tu API
server.port=8080

# Credenciales para la base de datos temporal (H2)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Le decimos que cree las tablas en memoria temporalmente
spring.jpa.hibernate.ddl-auto=create-drop